### ISSUE TITLE
custom formatting of dateFormat

### ISSUE THREAD

**Issue by lucasrohlf** [linuxsoftware/ls.joyous#17]
Is it possible to reformat the output of dateFormat(when) without editing telltime.py?

I have been trying via templatetags but I have had no luck so far.

**Comment by linuxsoftware** [comment]
No, sorry, in that old bit of code I was only thinking about my own preferences.

To fix this what do you think about having a couple of new settings ``JOYOUS_DATE_FORMAT`` and ``JOYOUS_TIME_FORMAT``.  If these are not set Joyous would default to using the standard Django formatting.  They would have the same options as https://docs.djangoproject.com/en/dev/ref/templates/builtins/#std:templatefilter-date, but with an addition so that the year is not displayed if it is the current year (perhaps "[Y]").

Would that meet your needs?

**Comment by linuxsoftware** [comment]
New settings ``JOYOUS_DATE_FORMAT``, ``JOYOUS_DATE_SHORT_FORMAT`` and ``JOYOUS_TIME_FORMAT`` now allow custom formatting of dateFormat, dateShortFormat (formerly known as dateFormatYMD) and timeFormat.
